# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BTRouteDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'DeepLinkKit', '~> 1.2.2'
  pod 'JSONModel', '~> 1.5.1'

    target 'BTRouteDemoTests' do
        inherit! :search_paths
    end

end
